import type { Metadata } from "next";
import "./globals.css";
import { QueryProvider } from "@/features/query/QueryProvider";
import localFont from "next/font/local"

import { Toaster } from "react-hot-toast";


const noto = localFont({
  variable: "--font-noto",
  display: "swap",
  src: [
    {
      path: "../public/font/NotoSansGeorgian-Regular.ttf",
      weight: "400",
      style: "normal"
    },
  ]
})

const mecomisce = localFont({
  variable: "--font-mecomisce",
  display: "swap",
  src: [
    {
      path: "../public/font/TFMecomicse-Regular-59522229166.otf",
      weight: "400",
      style: "normal"
    }
  ]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ka" className={`${noto.variable} ${mecomisce.variable}`}>
      <body>
        <QueryProvider>
          {children}
          <Toaster
            position="bottom-right"
            toastOptions={{
              style: {
                background: "#4E876D",
                color: "#fff",
              },
              success: {
                iconTheme: {
                  primary: "#fff",
                  secondary: "#4E876D",
                },
              },
              error: {
                style: {
                  background: "#ef4444",
                  color: "#fff",
                },
                iconTheme: {
                  primary: "#fff",
                  secondary: "#ef4444",
                },
              },
            }}
          />
        </QueryProvider>
      </body>
    </html>
  );
}
